# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "checkout customization draco"
client_id = "7bc0a414307dd63eb2fd7dbcfb0828e4"
application_url = "https://ethical-shakira-exactly-metadata.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ethical-shakira-exactly-metadata.trycloudflare.com/auth/callback",
  "https://ethical-shakira-exactly-metadata.trycloudflare.com/auth/shopify/callback",
  "https://ethical-shakira-exactly-metadata.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cqsubs.myshopify.com"
